{{- if .Values.redirector.enabled -}}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "chart.resourceNamePrefix" . }}redirector-config
type: Opaque
stringData:
  redirector.yml: |-
    db:
      host: {{ default (printf "%s-postgresql.%s" .Release.Name .Release.Namespace) .Values.db.host }}
      port: {{ .Values.db.port }}
      dbname: {{ .Values.db.dbname }}
      user: {{ .Values.db.user }}
      password: {{ .Values.db.password }}
    log:
      format: {{ .Values.log.format }}
    server:
      addr: {{ .Values.redirector.addr }}
      base_redirect_url: {{ .Values.redirector.baseRedirectUrl }}
{{- end }}
