[package]
name = "ocg-server"
description = "Open Alliance Groups server"
version.workspace = true
license.workspace = true
edition.workspace = true
rust-version.workspace = true

[dependencies]
anyhow = { workspace = true }
askama = { workspace = true }
base64 = { workspace = true }
async-trait = { workspace = true }
aws-credential-types = { workspace = true }
aws-sdk-s3 = { workspace = true }
axum = { workspace = true }
axum-login = { workspace = true }
axum-messages = { workspace = true }
bytes = { workspace = true }
cached = { workspace = true }
clap = { workspace = true }
chrono = { workspace = true }
chrono-tz = { workspace = true }
csv = { workspace = true }
deadpool-postgres = { workspace = true }
emojis = { workspace = true }
figment = { workspace = true }
futures-util = { workspace = true }
garde = { workspace = true }
hex = { workspace = true }
hmac = { workspace = true }
icalendar = { workspace = true }
image = { workspace = true }
lettre = { workspace = true }
markdown = { workspace = true }
mime_guess = { workspace = true }
minify-html = { workspace = true }
num-format = { workspace = true }
oauth2 = { workspace = true }
openidconnect = { workspace = true }
openssl = { workspace = true }
password-auth = { workspace = true }
percent-encoding = { workspace = true }
postgres-openssl = { workspace = true }
quick-xml = { workspace = true }
qrcode = { workspace = true }
reqwest = { workspace = true }
redis = { workspace = true }
rkyv = { workspace = true }
rust-embed = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
serde_qs = { workspace = true }
serde_urlencoded = { workspace = true }
serde_with = { workspace = true }
sha2 = { workspace = true }
strum = { workspace = true }
subtle = { workspace = true }
thiserror = { workspace = true }
time = { workspace = true }
tokio = { workspace = true }
tokio-postgres = { workspace = true }
tokio-util = { workspace = true }
tower = { workspace = true }
tower-http = { workspace = true }
tower-sessions = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
unicode-segmentation = { workspace = true }
uuid = { workspace = true }

[dev-dependencies]
mockall = { workspace = true }

[build-dependencies]
anyhow = { workspace = true }
hex = { workspace = true }
sha2 = { workspace = true }
which = { workspace = true }
