# Build server
FROM rust:1.96.0-alpine3.23 AS builder
ARG OCG_COMMIT_SHA
ENV OCG_COMMIT_SHA=$OCG_COMMIT_SHA
RUN apk --no-cache add musl-dev perl make
RUN wget -O /usr/local/bin/tailwindcss https://github.com/tailwindlabs/tailwindcss/releases/download/v4.1.10/tailwindcss-linux-x64-musl
RUN chmod +x /usr/local/bin/tailwindcss
WORKDIR /ocg
COPY Cargo.* ./
COPY ocg-redirector/Cargo.* ocg-redirector
COPY docs docs
COPY ocg-server ocg-server
WORKDIR /ocg/ocg-server
RUN cargo build --locked --release

# Final stage
FROM alpine:3.23.5
RUN apk --no-cache add ca-certificates postgresql17-client && addgroup -S ocg && adduser -S ocg -G ocg
USER ocg
WORKDIR /home/ocg
COPY --from=builder /ocg/target/release/ocg-server /usr/local/bin
