-- ============================================================================
-- SETUP
-- ============================================================================

begin;
select plan(166);

-- ============================================================================
-- TESTS
-- ============================================================================

-- Test: check tables have expected primary keys
select has_pk('attachment');
select has_pk('audit_log');
select has_pk('auth_session');
select has_pk('cfs_submission');
select has_pk('cfs_submission_rating');
select has_pk('cfs_submission_status');
select has_pk('alliance');
select has_pk('alliance_permission');
select has_pk('alliance_redirect_settings');
select has_pk('alliance_role');
select has_pk('alliance_role_alliance_permission');
select has_pk('alliance_role_group_permission');
select has_pk('alliance_site_layout');
select has_pk('alliance_team');
select hasnt_pk('alliance_views');
select has_pk('api_token');
select has_pk('custom_notification');
select has_pk('email_verification_code');
select has_pk('event');
select has_pk('event_attendee');
select has_pk('event_category');
select has_pk('event_discount_code');
select has_pk('event_host');
select has_pk('event_kind');
select has_pk('event_organizer');
select has_pk('event_purchase');
select has_pk('event_refund_request');
select has_pk('event_ticket_price_window');
select has_pk('event_ticket_type');
select has_pk('event_series');
select has_pk('event_speaker');
select has_pk('event_sponsor');
select hasnt_pk('event_views');
select has_pk('event_waitlist');
select has_pk('group');
select has_pk('group_category');
select has_pk('group_join_request');
select has_pk('group_member');
select has_pk('group_member_spotlight');
select has_pk('group_permission');
select has_pk('group_role');
select has_pk('group_role_group_permission');
select has_pk('group_site_layout');
select has_pk('group_sponsor');
select has_pk('group_store_item');
select has_pk('group_team');
select hasnt_pk('group_views');
select has_pk('images');
select has_pk('legacy_event_host');
select has_pk('legacy_event_speaker');
select has_pk('meeting');
select has_pk('meeting_auto_end_check_outcome');
select has_pk('meeting_provider');
select has_pk('notification');
select has_pk('notification_attachment');
select has_pk('notification_kind');
select has_pk('notification_template_data');
select has_pk('payment_provider');
select has_pk('region');
select has_pk('session');
select has_pk('session_kind');
select has_pk('session_proposal');
select has_pk('session_proposal_level');
select has_pk('session_proposal_status');
select has_pk('session_speaker');
select has_pk('site');
select has_pk('user');

-- Test: check tables have expected foreign keys
select col_is_fk('alliance', 'alliance_site_layout_id', 'alliance_site_layout');
select col_is_fk('alliance_redirect_settings', 'alliance_id', 'alliance');
select col_is_fk('alliance_role_alliance_permission', 'alliance_permission_id', 'alliance_permission');
select col_is_fk('alliance_role_alliance_permission', 'alliance_role_id', 'alliance_role');
select col_is_fk('alliance_role_group_permission', 'alliance_role_id', 'alliance_role');
select col_is_fk('alliance_role_group_permission', 'group_permission_id', 'group_permission');
select col_is_fk('alliance_team', 'alliance_id', 'alliance');
select col_is_fk('alliance_team', 'user_id', 'user');
select col_is_fk('alliance_views', 'alliance_id', 'alliance');
select col_is_fk('api_token', 'user_id', 'user');
select col_is_fk('custom_notification', 'created_by', 'user');
select col_is_fk('custom_notification', 'event_id', 'event');
select col_is_fk('custom_notification', 'group_id', 'group');
select col_is_fk('cfs_submission', 'event_id', 'event');
select col_is_fk('cfs_submission', 'reviewed_by', 'user');
select col_is_fk('cfs_submission', 'session_proposal_id', 'session_proposal');
select col_is_fk('cfs_submission', 'status_id', 'cfs_submission_status');
select col_is_fk('cfs_submission_rating', 'cfs_submission_id', 'cfs_submission');
select col_is_fk('cfs_submission_rating', 'reviewer_id', 'user');
select col_is_fk('email_verification_code', 'user_id', 'user');
select col_is_fk('event', 'event_category_id', 'event_category');
select col_is_fk('event', 'created_by', 'user');
select col_is_fk('event', 'event_kind_id', 'event_kind');
select col_is_fk('event', 'event_series_id', 'event_series');
select col_is_fk('event', 'group_id', 'group');
select col_is_fk('event', 'meeting_provider_id', 'meeting_provider');
select col_is_fk('event', 'published_by', 'user');
select col_is_fk('event_attendee', 'event_id', 'event');
select col_is_fk('event_attendee', 'user_id', 'user');
select col_is_fk('event_category', 'alliance_id', 'alliance');
select col_is_fk('event_discount_code', 'event_id', 'event');
select col_is_fk('event_host', 'event_id', 'event');
select col_is_fk('event_host', 'user_id', 'user');
select col_is_fk('event_organizer', 'event_id', 'event');
select col_is_fk('event_organizer', 'user_id', 'user');
select col_is_fk('event_purchase', 'event_discount_code_id', 'event_discount_code');
select col_is_fk('event_purchase', 'event_id', 'event');
select col_is_fk('event_purchase', 'payment_provider_id', 'payment_provider');
select col_is_fk('event_purchase', 'event_ticket_type_id', 'event_ticket_type');
select col_is_fk('event_purchase', 'user_id', 'user');
select col_is_fk('event_refund_request', 'event_purchase_id', 'event_purchase');
select col_is_fk('event_refund_request', 'requested_by_user_id', 'user');
select col_is_fk('event_refund_request', 'reviewed_by_user_id', 'user');
select col_is_fk('event_ticket_price_window', 'event_ticket_type_id', 'event_ticket_type');
select col_is_fk('event_ticket_type', 'event_id', 'event');
select col_is_fk('event_series', 'created_by', 'user');
select col_is_fk('event_series', 'group_id', 'group');
select col_is_fk('event_speaker', 'event_id', 'event');
select col_is_fk('event_speaker', 'user_id', 'user');
select col_is_fk('event_sponsor', 'event_id', 'event');
select col_is_fk('event_sponsor', 'group_sponsor_id', 'group_sponsor');
select col_is_fk('event_views', 'event_id', 'event');
select col_is_fk('event_waitlist', 'event_id', 'event');
select col_is_fk('event_waitlist', 'user_id', 'user');
select col_is_fk('group', 'alliance_id', 'alliance');
select col_is_fk('group', 'group_category_id', 'group_category');
select col_is_fk('group', 'group_site_layout_id', 'group_site_layout');
select col_is_fk('group', 'region_id', 'region');
select col_is_fk('group_category', 'alliance_id', 'alliance');
select col_is_fk('group_join_request', 'group_id', 'group');
select col_is_fk('group_join_request', 'reviewed_by', 'user');
select col_is_fk('group_join_request', 'user_id', 'user');
select col_is_fk('group_member', 'group_id', 'group');
select col_is_fk('group_member', 'user_id', 'user');
select col_is_fk('group_member_spotlight', 'created_by', 'user');
select col_is_fk('group_member_spotlight', 'group_id', 'group');
select col_is_fk('group_member_spotlight', 'user_id', 'user');
select col_is_fk('group_role_group_permission', 'group_permission_id', 'group_permission');
select col_is_fk('group_role_group_permission', 'group_role_id', 'group_role');
select col_is_fk('group_sponsor', 'group_id', 'group');
select col_is_fk('group_store_item', 'created_by', 'user');
select col_is_fk('group_store_item', 'group_id', 'group');
select col_is_fk('group_team', 'group_id', 'group');
select col_is_fk('group_team', 'role', 'group_role');
select col_is_fk('group_team', 'user_id', 'user');
select col_is_fk('group_views', 'group_id', 'group');
select col_is_fk('images', 'created_by', 'user');
select col_is_fk('legacy_event_host', 'event_id', 'event');
select col_is_fk('legacy_event_speaker', 'event_id', 'event');
select col_is_fk('meeting', 'auto_end_check_outcome', 'meeting_auto_end_check_outcome');
select col_is_fk('meeting', 'event_id', 'event');
select col_is_fk('meeting', 'meeting_provider_id', 'meeting_provider');
select col_is_fk('meeting', 'session_id', 'session');
select col_is_fk('notification', 'kind', 'notification_kind');
select col_is_fk('notification', 'notification_template_data_id', 'notification_template_data');
select col_is_fk('notification', 'user_id', 'user');
select col_is_fk('notification_attachment', 'attachment_id', 'attachment');
select col_is_fk('notification_attachment', 'notification_id', 'notification');
select col_is_fk('region', 'alliance_id', 'alliance');
select col_is_fk('session', 'event_id', 'event');
select col_is_fk('session', 'cfs_submission_id', 'cfs_submission');
select col_is_fk('session', 'meeting_provider_id', 'meeting_provider');
select col_is_fk('session', 'session_kind_id', 'session_kind');
select col_is_fk('session_proposal', 'co_speaker_user_id', 'user');
select col_is_fk('session_proposal', 'session_proposal_level_id', 'session_proposal_level');
select col_is_fk('session_proposal', 'session_proposal_status_id', 'session_proposal_status');
select col_is_fk('session_proposal', 'user_id', 'user');
select col_is_fk('session_speaker', 'session_id', 'session');
select col_is_fk('session_speaker', 'user_id', 'user');

-- ============================================================================
-- CLEANUP
-- ============================================================================

select * from finish();
rollback;
